# Generated by Django 2.0.13 on 2019-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190512_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FilePathField(path='static/img/cPZsn8GYw6c.jpg'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
