# Generated by Django 2.0.13 on 2019-05-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190512_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FilePathField(default='img/cPZsn8GYw6c.jpg'),
        ),
    ]
