# Generated by Django 2.0.13 on 2019-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190512_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
